/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-22 13:11:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>개인 회원 가입/수정</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/all.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".all-margin:before, .all-margin:after {\r\n");
      out.write("    content: '';\r\n");
      out.write("    display: table;\r\n");
      out.write("    clear: both;\r\n");
      out.write("}\r\n");
      out.write(".signup{\r\n");
      out.write("	margin: 80px 0;\r\n");
      out.write("}\r\n");
      out.write(".signup h4{\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	margin: 0 0 20px; \r\n");
      out.write("}\r\n");
      out.write(".section-title{\r\n");
      out.write("	border-top: 2px solid #222;\r\n");
      out.write("	margin: 50px 0 35px;\r\n");
      out.write("	padding: 50px 0 0;\r\n");
      out.write("}\r\n");
      out.write(".form-element{\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write(".signup .form-element {\r\n");
      out.write("    max-width: 700px;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write(".signup .form-element:before, .signup .form-element:after {\r\n");
      out.write("    content: '';\r\n");
      out.write("    display: table;\r\n");
      out.write("}\r\n");
      out.write(".signup .form-element:after {\r\n");
      out.write("    clear: both;\r\n");
      out.write("}\r\n");
      out.write(".form-label{\r\n");
      out.write("    float: left;\r\n");
      out.write("    line-height: 46px;\r\n");
      out.write("    width: 150px;\r\n");
      out.write("}\r\n");
      out.write("label {\r\n");
      out.write("    color: #787878;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-textbox{\r\n");
      out.write("	float: left;\r\n");
      out.write("    width: calc(100% - 150px);\r\n");
      out.write("    border: 1px solid #c5c5c5;\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    height: 46px;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    padding: 12px 15px;\r\n");
      out.write("}\r\n");
      out.write(".textbox-button {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    border: 1px solid #c5c5c5;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    height: 46px;\r\n");
      out.write("    line-height: 44px;\r\n");
      out.write("    padding: 0 20px;\r\n");
      out.write("    bottom: auto;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"text\"]{\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    height: 46px;\r\n");
      out.write("    padding: 12px 15px;\r\n");
      out.write("    width: calc(100% - 150px);\r\n");
      out.write("    border: 1px solid #c5c5c5;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"radio\"]{\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("    margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write(".form-title {\r\n");
      out.write("    border-top: 1px solid #dcdcdc;\r\n");
      out.write("    margin: 50px 0 30px;\r\n");
      out.write("    padding-top: 50px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".signup .zipcode {\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write(".zipcode .MS_input_txt {\r\n");
      out.write("    border: 1px solid #c5c5c5;\r\n");
      out.write("    border-right: none;\r\n");
      out.write("    float: left;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    height: 46px;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    padding: 12px 15px;\r\n");
      out.write("    width: 220px;\r\n");
      out.write(" }\r\n");
      out.write(" .signup .zipcode .textbox-button {\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("}\r\n");
      out.write(" .addresses {\r\n");
      out.write("    padding-left: 150px;\r\n");
      out.write("}\r\n");
      out.write(".addresses .form-textbox {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write(".signup-button {\r\n");
      out.write("    margin-top: 50px;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("}\r\n");
      out.write(".signup-button .button {\r\n");
      out.write("    max-width: 350px;\r\n");
      out.write("}\r\n");
      out.write(".sub_button {\r\n");
      out.write("    border-width: 2px;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    line-height: 50px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".signup-button input {\r\n");
      out.write("    max-width: 350px;\r\n");
      out.write("    background-color: transparent;\r\n");
      out.write("    border: 2px solid #222;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("        <!-- CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/ootm/component/header/header.css\"/>\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/ootm/component/footer/footer.css\"/>\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/ootm/css/reset.css\"/>\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/ootm/css/test.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header-component logoDark=\"true\" logoHoverDark=\"true\" mTextColor=\"black\" bgHoverColor=\"#F9F9F9\"></header-component>	\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"all-margin\">\r\n");
      out.write("		<div class=\"page-header\">\r\n");
      out.write("			<h2>Sign Up</h2>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"signup form-group\">\r\n");
      out.write("			<form name=\"form1\" method=\"post\" id=\"join_form\" action=\"/shop/idinfo.html\">\r\n");
      out.write("				<div class=\"section-title\">\r\n");
      out.write("					<h4>회원 정보</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-element\">\r\n");
      out.write("					<label class=\"form-label\">이름</label> <input type=\"text\"\r\n");
      out.write("						name=\"hname\" id=\"hname\" value=\"\" class=\"MS_input_txt form-textbox\"\r\n");
      out.write("						size=\"15\" maxlength=\"30\"/>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-element\">\r\n");
      out.write("					<label class=\"form-label\">아이디</label> <input type=\"text\" name=\"id\"\r\n");
      out.write("						id=\"id\" value=\"\" class=\"form-textbox\" size=\"10\" maxlength=\"12\">\r\n");
      out.write("					<a href=\"#\" class=\"textbox-button\">중복확인</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-element email\">\r\n");
      out.write("					<label class=\"form-label\">이메일주소</label> <input type=\"hidden\"\r\n");
      out.write("						name=\"oldemail\" value=\"\"> <input type=\"text\" name=\"email\"\r\n");
      out.write("						id=\"email\" class=\"MS_input_txt MS_input_txt06\" size=\"20\"\r\n");
      out.write("						maxlength=\"35\">\r\n");
      out.write("					<a href=\"\" class=\"textbox-button\">중복확인</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-element\">\r\n");
      out.write("					<label class=\"form-label\">비밀번호</label> <input type=\"password\"\r\n");
      out.write("						name=\"password1\" id=\"password1\" class=\"MS_input_txt form-textbox\"\r\n");
      out.write("						value=\"\" size=\"15\" maxlength=\"20\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-element\">\r\n");
      out.write("					<label class=\"form-label\">비밀번호확인</label> <input type=\"password\"\r\n");
      out.write("						name=\"password2\" id=\"password2\" class=\"MS_input_txt form-textbox\"\r\n");
      out.write("						value=\"\" size=\"15\" maxlength=\"20\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-element date-of-birth\">\r\n");
      out.write("					<label class=\"form-label\">생일/성별</label> <input type=\"tel\"\r\n");
      out.write("						name=\"birthyear\" class=\"MS_input_txt\" size=\"6\"\r\n");
      out.write("						maxlength=\"4\">년 <input type=\"tel\" name=\"birthmonth\"\r\n");
      out.write("						class=\"MS_input_txt\" size=\"4\" maxlength=\"2\">월 <input\r\n");
      out.write("						type=\"tel\" name=\"birthdate\" class=\"MS_input_txt\" size=\"4\"\r\n");
      out.write("						maxlength=\"2\">일&nbsp;&nbsp;<label><input\r\n");
      out.write("						type=\"radio\" name=\"sex\" value=\"-\" class=\"input-radio MS_radio\">\r\n");
      out.write("						선택안함</label> &nbsp;<label><input type=\"radio\" name=\"sex\" value=\"1\"\r\n");
      out.write("						checked=\"checked\" class=\"MS_radio MS_radio\">남</label> <label><input\r\n");
      out.write("						type=\"radio\" name=\"sex\" value=\"2\" class=\"MS_radio MS_radio\">여</label>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"form-title\">\r\n");
      out.write("					<h4>기본 배송지</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-element zipcode\">\r\n");
      out.write("					<label class=\"form-label\">주소</label> <input type=\"text\"\r\n");
      out.write("						name=\"hpost\" form=\"join_form\" id=\"hpost\" class=\"MS_input_txt\"\r\n");
      out.write("						value=\"\" size=\"7\" maxlength=\"15\" readonly=\"readonly\"> <a\r\n");
      out.write("						href=\"#\" class=\"textbox-button\">우편번호 검색</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-element addresses\">\r\n");
      out.write("					<input type=\"text\" name=\"haddress1\" form=\"join_form\" id=\"haddress1\"\r\n");
      out.write("						class=\"MS_input_txt form-textbox\" value=\"\" size=\"40\"\r\n");
      out.write("						maxlength=\"100\" readonly=\"readonly\"> <input type=\"text\"\r\n");
      out.write("						name=\"haddress2\" form=\"join_form\" id=\"haddress2\"\r\n");
      out.write("						class=\"MS_input_txt form-textbox\" placeholder=\"나머지 주소 입력\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-element\">\r\n");
      out.write("					<label class=\"form-label\">연락처</label> <input type=\"text\"\r\n");
      out.write("						name=\"hphone\" form=\"join_form\" id=\"hphone\"\r\n");
      out.write("						class=\"MS_input_tel form-textbox\" size=\"15\" maxlength=\"30\"\r\n");
      out.write("						value=\"\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-element\">\r\n");
      out.write("					<label class=\"form-label\">휴대폰</label> <input type=\"text\"\r\n");
      out.write("						name=\"etcphone\" form=\"join_form\" id=\"etcphone\"\r\n");
      out.write("						class=\"MS_input_tel form-textbox\" size=\"15\" maxlength=\"30\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"form-title\">\r\n");
      out.write("					<h4>선택 정보</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-element\">\r\n");
      out.write("					<label class=\"form-label\">추천인</label> <input type=\"text\"\r\n");
      out.write("						name=\"recommand_id\" id=\"recommand_id\" class=\"form-textbox\"\r\n");
      out.write("						size=\"15\" maxlength=\"12\"> <a\r\n");
      out.write("						href=\"#\" class=\"textbox-button\">아이디 확인</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"signup-button\">\r\n");
      out.write("					<input type=\"submit\" value=\"가입하기\" class=\"sub_button\" />\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"footer\">\r\n");
      out.write("	<footer-component/>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"../component/header/header.js\"></script>\r\n");
      out.write("    <script src=\"../component/footer/footer.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
